import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/theme/theme-provider";
import { AuthProvider } from "@/context/Auth/AuthProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`background-gradient-light dark:background-gradient-dark ${inter.className}`}
      >
        <AuthProvider>
          <ThemeProvider>
            <div className=" w-full h-full ">
              <Navbar />
              <div className="w-full h-[calc(100%-57px)]">{children}</div>
            </div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
